services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P455w0Rd!
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      # - $HOME/Documents/referrer-emailer-db-primary-mongostore:/data/db
      - ./mongostore:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: P455w0Rd!
      ME_CONFIG_MONGODB_URL: mongodb://root:P455w0Rd!@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  
  pdf-service:
    image: pdf-service:latest
    restart: always
    build:
      context: pdf-service
      dockerfile: Dockerfile
    environment:
      PORT: 3001
    ports:
      - 3001:3001
    expose:
      - 3001
    depends_on:
      - mongo

networks:
  referrer-mailer-subnet:
