package core

import (
	"errors"
	"fmt"

	"cloud.google.com/go/vertexai/genai"
)

// ResumeParser parses the resume from the given file path and returns the plain text content.
func (co *Core) ResumeParser(resumePath string) error {
	co.Lo.Info("started parsing", "resume", resumePath)

	ctx, cancel := getContextWithTimeout(10)
	defer cancel()

	part := genai.FileData{
		MIMEType: "application/pdf",
		FileURI:  "gs://sounish-cloud-workstation/referrer-uploads/Sounish_Nath_Resume_25.pdf",
	}

	res, err := co.llm.GenerateContent(ctx, part, genai.Text(`
			You are a very professional document summarization specialist.
    		Please summarize the given document.
	`))
	if err != nil {
		return fmt.Errorf("unable to generate contents: %w", err)
	}

	if len(res.Candidates) == 0 ||
		len(res.Candidates[0].Content.Parts) == 0 {
		return errors.New("empty response from model")
	}

	co.Lo.Info("generated by AI", "response", res.Candidates[0].Content.Parts[0])
	return nil
}
